### ISSUE TITLE
Issues with menu 

### ISSUE THREAD

**Issue by daktras420** [LBCrion/sfwbar#75] opened 2023-02-08 19:59 UTC
Ill try later to see if compiling from you mast branch has fixed this but I am using your project on labwc for my wm and lxqt for my desktop and application base. but too many applications are in the system  section of the menu, and makes it so many apps can't be used thank god for wofi that allow ws me to easily access apps but would love in the future to either be able to edit the application menu or if a wingmemu or a scroll abilty be added to the menu would be nice simular to the plug in for nwg wingmenu plugin. I find your project seems to work better for my needs and thanks for all you do.

**Comment by LBCrion** [comment] 2023-02-09 18:41
Hi, are you experiencing this issue with a start menu in w10.config? Do you see the menu expanding beyond the dimensions of the screen due to too many items being added to it?

**Comment by daktras420** [comment] 2023-02-09 18:45
Yes i am

**Comment by daktras420** [comment] 2023-02-09 21:55
Thank you very much

**Comment by LBCrion** [comment] 2023-02-10 20:25
This appears to be caused by interaction between gtk and gtk-layer-shell. Gtk window sizing code seems to break with layer shell windows. I'm trying to figure out if there is a way to work around this problem, but it's rather tricky.

**Comment by daktras420** [comment] 2023-02-10 20:48
Ok, thanks.

**Comment by LBCrion** [comment] 2023-02-12 21:09
This should be fixed in the latest git version.

**Comment by Consolatis** [comment] 2023-02-13 05:17
Nice one. I totally might steal this logic for some other project :)

I wonder if this could be fixed in gtk-layershell instead: if you keep `use_layershell=True` on the bottom of the example below, it doesn't render the scroll indicators for me. If you change that to `False` (e.g. make it a usual wayland client) it will render the scroll indicators but still ignores the exclusive zone settings by layershell clients (at least for me, on labwc).

That second part of the issue (`False` -> usual gtk wayland client -> ignoring the exclusive areas might point to an issue in labwc, will investigate this further), the first part of the issue however could potentially be further investigated and dealt with by gtk-layershell.

<details><summary>Python reproducer</summary>

```python
#!/usr/bin/env python3

import gi
gi.require_version("Gtk", "3.0")
gi.require_version('GtkLayerShell', '0.1')
from gi.repository import Gtk, GtkLayerShell

class Window(Gtk.Window):
	def __init__(self, use_layershell):
		super().__init__()
		if use_layershell:
			GtkLayerShell.init_for_window(self)
			GtkLayerShell.set_layer(self, GtkLayerShell.Layer.TOP)
		self.tray = Gtk.MenuBar()
		self.add(self.tray)
		self.tray.add(self.overflow_menu())
		self.set_default_size(200, -1)
		self.show_all()

	def overflow_menu(self):
		menu = Gtk.Menu()
		menu.add(Gtk.MenuItem(label="FooBar"))
		menu.add(Gtk.MenuItem(label="BarFoo"))

		overflow_menu = Gtk.Menu()
		for i in range(200):
			overflow_menu.add(Gtk.MenuItem(label=f"Overflow-{i:>3d}"))
		overflow_item = Gtk.MenuItem(label="Overflow")
		overflow_item.set_submenu(overflow_menu)
		menu.add(overflow_item);

		menuitem = Gtk.MenuItem(label="foobar")
		menuitem.set_submenu(menu)
		return menuitem

def main():
	win = Window(use_layershell=True)
	win.connect('destroy', Gtk.main_quit)
	try:
		Gtk.main()
	except KeyboardInterrupt:
		print()

if __name__ == '__main__':
	main()
```

</details>

**Comment by Consolatis** [comment] 2023-02-13 08:25
> The workarea in Gdk falls back to monitor geometry if the platform doesn't have a concept of workarea. SO far I haven't seen any wayland compositors where workarea would be adjusted for layer shell clients.

That is very useful to know. Thanks for sharing your research.

**Comment by Consolatis** [comment] 2023-02-13 10:58
> I think it would be difficult, since layer clients don't necessarily span the entire screen in either dimension, so workarea can be non-rectangular in theory

The [protocol](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml#L152) says this about exclusive zone:

        A positive value is only meaningful if the surface is anchored to one
        edge or an edge and both perpendicular edges. If the surface is not
        anchored, anchored to only two perpendicular edges (a corner), anchored
        to only two parallel edges or anchored to all edges, a positive value
        will be treated the same as zero.

I am not sure what that means in the centered on one edge case though. If the whole edge will then be reserved that should make sure that the resulting available geometry / workspace area is always rectangular. I am not sure though if there is an official (or at least wlr) wayland protocol to relay that information to clients. (Short of faking output geometries which would then be wrong for the fullscreen case).

**Comment by LBCrion** [comment] 2023-02-13 18:00
I just had a quick look at the gdk source and get_workarea method isn't defined for GdkWaylandMonitor class. This means at least in the current gtk3 implementation we're using the output geometry to place menus.

**Comment by kode54** [comment] 2024-04-03 08:08
I have a different problem with the menu. It seems as if the menu items overflow, and after a certain number of applications, it just stops listing.

Upon further testing, it turns out that the game "No Man's Sky" inserts an unescaped single-quote into the stream of text.

**Comment by LBCrion** [comment] 2024-04-03 09:18
This should be a reasonably easy fix.  The menu is generated by a python
script and indeed, it doesn't sanitise for a single quote. I'll have a look
at it once I'm back next week.

In the meantime,  can you post a .desktop file for No Man's Sky? It would
be good to have an example to test against.

**Comment by LBCrion** [comment] 2024-04-07 08:46
@kode54, I updated the python script in `startmenu.widget` to sanitize the app names for single quotes. This should hopefully fix the issue.

**Comment by LBCrion** [comment] 2024-06-15 18:47
I think this is fixed now. If you run into this again, please feel free to reopen.

**Closed by LBCrion** 2024-06-15 18:47 UTC
