### ISSUE TITLE
How to place the bar to the left of the screen

### ISSUE THREAD

**Issue by devosalain** [LBCrion/sfwbar#6] opened 2021-08-07 13:29 UTC
The bar works fine on FreeBSD13.0.
But how to place the bar to the left on the screen instead of the bottom ?

**Comment by LBCrion** [comment] 2021-08-09 19:21
I just added the option to specify the edge of the screen (latest commit in the main branch). You can specify the edge in the css as following: window { -GtkWidget-direction: left; }

Can you please test it and see if it does what you want?

(You will probably need to change the direction of the grid#layout to bottom, so the widgets stack vertically).

**Comment by devosalain** [comment] 2021-08-10 17:30
It worked. Cool.

**Comment by LBCrion** [comment] 2021-08-12 18:52
Fixed in trunk for 0.99 release.

**Closed** 2021-08-12 18:52 UTC

**Comment by clemencyworld1** [comment] 2022-09-18 10:57
I followed the instruction but it did not work for me. I used external plugins, do i need to change their widget directions too. I will want the bar on the right and centered.

**Comment by clemencyworld1** [comment] 2022-09-18 11:03
function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "top"
#  SetMonitor "eDP-1"
#  SetBarSize "800" 
}

function("ToggleMinimize") {
  [!Minimized] Minimize
  [Minimized] UnMinimize
}

function("ToggleMaximize") {
  [!Maximized] Maximize
  [Maximized] UnMaximize
}

menu("winops") {
  item("focus", Focus );
  item("close", Close );
  item("(un)minimize", Function "ToggleMinimize" );
  item("(un)maximize", Function "ToggleMaximize" );
}

# Panel layout

layout {

  
# add a launcher

 label { css = "* { -GtkWidget-hexpand: true; }" }

grid {
    css = "* { border-radius: 180px 180px 0px 0px; padding: 5px 50px; background: linear-gradient(to top, rgba(105, 15, 1, 0.5) 0%, rgba(15, 15, 15, 0.5) 30%, rgba(155, 155, 155, 0.5) 30%, rgba(255, 255, 255, 0.1) 40%,  rgba(0, 0, 0, 1.0) 57%, rgba(255, 255, 255, 0.0) 62% );}" # stretch horizontally


  button {
    value = "utilities-terminal-symbolic"
    action = "xterm"                         
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; min-width: 0.7cm; min-height: 0.7cm; background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); border-width: 2px; border-radius: 30px;}";
  }

  button {
    value = "folder"
    action = "spacefm"                        
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; min-width: 0.7cm; min-height: 0.7cm; background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); border-width: 2px; border-radius: 30px;}";
  }
  
  button {
    value = "web-browser"
    action = "seamonkey"                         
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; min-width: 0.7cm; min-height: 0.7cm; background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); border-width: 2px; border-radius: 30px;}";
  }


  taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: false; padding: 0px 5px 0px 5px;}" 
    icons = true
    labels = false
    filter_output = true
    action[3] = Close
  }
}

 label { css = "* { -GtkWidget-hexpand: true; }" }

}



#CSS

window#sfwbar {
  -GtkWidget-direction: right;
background: rgba(255, 255, 255, 0.0);
}

button#taskbar_normal image, button#taskbar_active image, button#taskbar_normal:hover image {
  min-width: 0.8cm;
  min-height: 0.8cm;
}

button#taskbar_normal , button#taskbar_active , button#taskbar_normal:hover {
background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  );
 border-radius: 30px;
border-width: 2px;
margin: 3px 4px 30px 4px;
  border-image: none;
  -GtkWidget-hexpand: false;
    box-shadow: 2px 1px 2px 1px #000fff;
padding: 12px;
}

button  {
margin: 3px 4px 30px 4px;
padding: 15px;
}


button#taskbar_active {
background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 155, 155, 0.8)95%  );
    box-shadow: 2px 1px 2px 1px #FF3333;
 }

button#taskbar_normal:hover, button#taskbar_active:hover {
  background-color: rgba(255, 255, 155, 0.5);
  border: none;
}

image#tray_active, image#tray_passive, image#tray_attention {
margin: 4px;    
box-shadow: 2px 1px 2px 1px #ffffff; 
min-width: 0.9cm; 
min-height: 0.5cm; 
background: #000fff; 
border-width: 0px; 
border-radius: 30px;
padding: 10px;
}

grid#layout {
  -GtkWidget-direction: bottom;
padding: 10px;
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:09
This is my sfwbar.config. My plugin config are listed below. Unfortunately, am no able to drop the files unto github.

**Comment by clemencyworld1** [comment] 2022-09-18 11:10
scanner {
# Poll current_backlight
  file("/sys/class/backlight/*/actual_brightness") {
    BacklightActual = Grab(Sum)
  }
  file("/sys/class/backlight/*/max_brightness") {
    BacklightMax = Grab(Sum)
  }
}

layout {
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false;  font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff;   margin: 4px;}"
  label {
  css = "* { padding: 2px;}"
    value = ""
  }

  label {
   css = "* { padding: 2px;}"
   style = "backlight"
    interval = 2000
    value = Str(BacklightActual/BacklightMax*100,0) +
          '% '
  }
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:10
scanner {
# Get total and remaining battery charge
  file("/sys/class/power_supply/BAT0/energy_full") {
    BatteryTotal = Grab(Sum)
  }
  file("/sys/class/power_supply/BAT0/energy_now") {
    BatteryLeft = Grab(Sum)
  }
}

layout {
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false;  font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff;  margin: 4px; }"

  label {
  css = "* { padding: 2px;}"
    style = "value_icon"
    value =           if(BatteryLeft/BatteryTotal < .2,"", 
          if(BatteryLeft/BatteryTotal < .4,"", 
          if(BatteryLeft/BatteryTotal < .6,"", 
          if(BatteryLeft/BatteryTotal < .8,"",""))))
  }

  label {
  css = "* { padding: 2px;}"
    style = "battery"
    interval = 60000
    value = Str(BatteryLeft/BatteryTotal*100,0) + '% '
}
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:10
layout {
  style = "frame"
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false;  font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff;   margin: 4px; }"

  label {
    style = "time"
    interval = 1000
    css = "* { -GtkWidget-align: 0.5; -GtkWidget-hexpand: true; -GtkWidget-vexpand: true; padding: 2px; }"
    value = Time("%r")
        action = "yad --calendar"
  }

  label {
    style = "date"
    interval = 1000
    css = "label { -GtkWidget-align: 0.5; -GtkWidget-hexpand: true; -GtkWidget-vexpand: true; }"
    value = Time(" - %d/%b/%Y")
    action = "yad --calendar"
  }
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:11
scanner {
# Poll volume statistics from pulseaudio

  exec(" amixer sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }'") {
    Volume = Grab()
  }
}

layout {
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false; font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff; margin: 4px;}"
  label {
  css = "* { padding: 2px;}"
    style = "value_icon"
    value = If(Volume=0,"Muted",If(Volume<33,"",If(Volume<66,"",""))) )
  }
  label {
   css = "* { padding: 2px;}"
   style = If(Mute=1,"pulseaudio_muted","pulseaudio")
    value = Str(Volume,0) + "% " 
    action = amixer set Master 5%+"
    action[3] = amixer set Master 5%-"
  }
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:11
scanner {
# Add up received and transmitted bytes cross all enp* interfaces  
  file("/proc/net/dev") {
    EthRcvd = RegEx("wl.*:[\t ]*([0-9]+)",Sum)
    EthSent = RegEx("wl.*:(?:[\t ]*[0-9]+){8}[\t ]([0-9]+)",Sum)
  }
}

layout {
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false; font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff;  margin: 4px;}"
label {
   css = "* { padding: 2px;}"
   style = "value_icon"
    value = ""
  }
  label {
   css = "* { padding: 2px;}"
   style = "value"
    interval = 1000
    value = Str((EthRcvd-EthRcvd.pval)/0.001024/EthRcvd.time,0)+"K/s"
  }
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:12
scanner {
# Poll wlan0 statistics
  file("/proc/net/dev") {
    NetDev = RegEx("^[\t ]*(.*(?<!lo)):",First)
  }
  file("/proc/net/wireless") {
    WifiInterface = RegEx("^(.*):",First)
    WifiSignal = RegEx(":[\t ]*-?[0-9]+\.?[\t ]*-?[0-9]+\.?[\t ]*(-?[-0-9]+)",First)
  }
  file("/sys/class/net/*/carrier_*_count") {
    NetCount = Grab(Sum)
  }
  exec("/usr/sbin/iw dev;ip addr") {
    WifiSsid = RegEx("ssid (.*)$")
    NetIp = RegEx("inet ([0-9\./]*(?<!127.0.0.1/8)) ",First)
  }
}

define WifiQuality = (100 - (-20 - WifiSignal) * 77/65)

function("ToggleNet") {
  [UserState] UserState "off"
  [UserState] SetValue If($WifiInterface="",If($NetDev="","Disconnected",
    $NetDev + ": " + If(Cached(NetCount) = NetCount,Cached($NetIp), $NetIp)),
    $NetDev + ": " + If(Cached(NetCount) = NetCount,Cached($NetIp), $NetIp))
  [!UserState] UserState "on"
  [!UserState] SetValue If($WifiInterface="",If($NetDev="","Disconnected",
        $NetDev + ": " + 
        If(Cached(NetCount) = NetCount,Cached($NetIp), $NetIp) + " "),
        If(Cached(NetCount) = NetCount,Cached($WifiSsid), $WifiSsid) +
        " (" + Str(WifiQuality,0) + "%) ")
}

layout {
  css = "* { -GtkWidget-direction: right; -GtkWidget-vexpand: false; -GtkWidget-hexpand: false;  font-size: 18; font-weight: bold; text-shadow: 0px 2px #000000; color: #ffffff;  margin: 4px; }"
label {
  css = "* { padding: 2px;}"
    style = "value_icon"
    value =  ""
  }
  label {
  css = "* { padding: 2px;}"
    style = "network"
    interval = 6000
    action = Function "ToggleNet"
    action[0] = Function "ToggleNet"
  }
}

**Comment by clemencyworld1** [comment] 2022-09-18 11:12
I used awesome font for my icon font. Sorry for the bother.

**Comment by clemencyworld1** [comment] 2022-09-18 11:24
Changing widget direction for the window to 'bottom' centers the bar at the bottom of the screen which is expected but when set to 'right' goes to the top right corner.

**Comment by clemencyworld1** [comment] 2022-09-18 11:28
Also i will like to  know how to theme the static button when hovered just like the taskbar button. 

Thanks in advance

**Comment by LBCrion** [comment] 2022-09-18 12:06
Which compositor are you using? SetBarSize on a right edge panel should remove top and bottom anchors, which most compositors interpret as center alignment of the bar on the remaining anchored edge (right in your case). I just tested this on sway and labwc and both centered my panel on the right (I used a vertical.config with window style changed to ```-GtkWidget-direction: right``` and ```SetbarSize "800px"``` added to the SfwbarInit function).
Also, are you running any other layer-shell applications? In theory these could push the bar out of centered alignment. 

As for theming the button, you should be able to theme it using a css ```:hover``` modifier. I.e.
```
button#mystyle:hover {
background-color: red;
}
```

or if you're adding this via css =  property, you just use ```css = "button:hover { background-color:red; }"```

**Comment by clemencyworld1** [comment] 2022-09-19 19:43
Sorry I did not mention, am running it on wayfire. Apart from running another instance of sfwbar as panel, I am using https://github.com/AhoyISki/wayfire-firedecor.git for window decoration.

**Comment by clemencyworld1** [comment] 2022-09-19 19:44
I will try the button theme when I get home. But, how do I set "my style" for the widgets?

Thanks for swift response.

**Comment by clemencyworld1** [comment] 2022-09-20 03:30
I figured it out:

  button {
  style = "icon"
    value = "folder"
    action = "spacefm"                        
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; min-width: 0.5cm; min-height: 0.5cm; background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); border-width: 2px; border-radius: 30px;}";
  }

then under #css

button#icon:hover  {
  background-color: rgba(255, 255, 155, 0.5);
  border: none;
}

**Comment by clemencyworld1** [comment] 2022-09-20 03:34
Setting the bar size did not work for me. vertical.config works though. So, i think i will start up with vertical.config as template.

**Comment by clemencyworld1** [comment] 2022-09-20 05:05
I noticed something. Since my widgets are in a grid, I have to set style property for it and change its widget direction. But the problem is that while the custom buttons are aligned vertically;  taskbar buttons are aligned horizontally. Still trying to make both align in the same direction so they appear as a single dock.

**Comment by LBCrion** [comment] 2022-09-20 06:53
For taskbar, you can specify either a number of columns or rows. For vertical config, you want to add ```cols = 1``` property to taskbar declaration and make sure there is no ```rows = ``` property defined.

**Comment by LBCrion** [comment] 2022-09-20 07:12
The bar placement going to the top right corner looks to be a wayfire issue. wlr layer shell protocol (which i what bars use to request placement in a correct position and layer from the compositor) uses anchors to specify where the bar attaches to the edges of the window. When you specify -GtkWidget-direction: right on the bar and call SetBarSize on it, the only anchor the bar requests is the right one. Most compositors interpret this as placement on the right edge, centered vertically, but I don't think there is a specific requirement to center. Wayfire seems to interpret it as placement on the top right. This is more consistent with both top and right anchors being requested, so it could be worth checking with wayfire team if this feature works as intended.

**Comment by clemencyworld1** [comment] 2022-09-20 17:47
I was able to get it right using vertical.config as template. Changing "rows = 1" to "cols = 1" was indeed helpful. I am not sure of other changes i made; really took some time to get it work.

**Comment by clemencyworld1** [comment] 2022-09-20 17:50
function("SfwbarInit") {
  SetLayer "bottom"
  SetMonitor "eDP-1"
SetBarSize "900"
}

function("ToggleMinimize") {
  [!Minimized] Minimize
  [Minimized] UnMinimize
}

function("ToggleMaximize") {
  [!Maximized] Maximize
  [Maximized] UnMaximize
}

menu("winops") {
  item("focus", Focus );
  item("close", Close );
  item("(un)minimize", Function "ToggleMinimize" );
  item("(un)maximize", Function "ToggleMaximize" );
}
# Panel layout

layout {


  label {
    css = "* { -GtkWidget-vexpand: true; }"
  }

grid {
  style = "alpha"
  
  # add a launcher
  button {
  style = "launcher"
    value = "utilities-terminal-symbolic"
    action = "xterm"                         
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; 
    background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); 
    border-width: 2px; 
    border-radius: 30px;}";
  }

  button {
  style = "launcher"
    value = "folder"
    action = "spacefm"                        
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; 
    background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); 
    border-width: 2px; 
    border-radius: 30px;}";
  }
  
  button {
  style = "launcher"
    value = "web-browser"
    action = "seamonkey"                         
    css = "* { box-shadow: 2px 1px 2px 1px #000fff; 
    background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95%  ); 
    border-width: 2px; 
    border-radius: 30px;}";
  }
 
   # add a taskbar
  taskbar {
css = "* { -GtkWidget-hexpand: false; }"
    icons = true     # display icons
    labels = false   # don't display titles
    cols = 1        
    action[3] = Menu "winops"
  }
}

  label {
    css = "* { -GtkWidget-vexpand: true; }"
  }

}

#CSS
window#sfwbar {
  -GtkWidget-direction: right;
  background: transparent;
}

button#taskbar_normal image, button#taskbar_active image, button#taskbar_normal:hover image {
min-width: 0.5cm;
min-height: 0.5cm;
}

button#launcher image {
min-width: 0.4cm;
min-height: 0.4cm;
}

button#launcher {
min-width: 0.6cm;
min-height: 0.6cm;
padding: 5px;
}

button#taskbar_normal, button#taskbar_active, button#taskbar_normal:hover {
background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 255, 255, 0.8)95% );
-GtkWidget-hexpand: false;
box-shadow: 2px 1px 2px 1px #000fff;
-GtkWidget-direction: right;
border-radius: 30px;
min-width: 0.6cm;
min-height: 0.6cm;
 }

grid#alpha {
  -GtkWidget-direction: bottom;
padding: 30px 5px 30px 5px;
 border-radius: 180px 0px 0px 180px;
background: linear-gradient(to left, rgba(15, 15, 1, 0.5) 0%, rgba(15, 15, 15, 0.5) 10%, rgba(155, 155, 155, 0.5) 0%, rgba(255, 255, 255, 0.1) 40%, rgba(0, 0, 0, 1.0) 57%, rgba(255, 255, 255, 0.0) 62% );
}


button#taskbar_normal:hover, button#taskbar_active:hover, button:hover {
margin: 3px 4px 3px 4px;
}

button {
margin: 5px;
padding: 5px;
}


button#taskbar_active {
background: linear-gradient(to bottom, rgba(0, 100, 0, 1.0)0%, rgba(0, 0, 0, 1.0)30%, rgba(255, 155, 155, 0.8)95% );
box-shadow: 2px 1px 2px 1px #FF3333;
}

grid#layout {
  -GtkWidget-direction: bottom;
}

**Comment by clemencyworld1** [comment] 2022-09-20 17:50
This is the final config

**Comment by clemencyworld1** [comment] 2022-09-20 17:57
![1](https://user-images.githubusercontent.com/42145055/191330144-0d0e946a-eace-4f49-8c31-4f5c6629d95f.png)
And the screenshot

**Comment by clemencyworld1** [comment] 2022-09-20 17:57
Thanks for your immense support. Will now mark as solved

**Comment by LBCrion** [comment] 2022-09-21 17:23
Wow. This is really nice! 

A few comments:
1) You can probably remove SetBarSize command, since you're centering the bar using expandable labels. On a larger displays, SetBarSize "900" will cause the bar to be centered withing the top 900 vertical pixels.
2) On my setup, the taskbar icons are not centered within the button, to ensure they are always centered, you can change the taskbar image CSS to:
```
button#taskbar_normal image, button#taskbar_active image, button#taskbar_normal:hover image {
min-width: 0.5cm;
min-height: 0.5cm;
-GtkWidget-hexpand: true;
-GtkWidget-vexpand: true;
-GtkWidget-halign: center;
-GtkWidget-valign: center;
}
```
3) Since you're using the same CSS for all launchers, you can just assign a style to them and move the CSS to the #CSS section.
4) I'm looking to build a gallery of screenshots and configs showing possible setups of the bar. Would you mind if I use your config/screenshot for this?

**Comment by LBCrion** [comment] 2022-09-21 17:25
Also, it looks like wayfire not centering the bar is a known issue: https://github.com/WayfireWM/wayfire/issues/936
