### ISSUE TITLE
Tray Connot Display Anything

### ISSUE THREAD

**Issue by Kratorisa** [LBCrion/sfwbar#26] opened 2022-04-10 23:14 UTC
OS: Fedora
Compositor: [LabWC](https://github.com/labwc/labwc)
Problem:

1 - Well, It is a complex problem, When I use SFWBar tray, No tray was displayed(I use the repo of copr, which is maintained by Crion.).

2 - If I start WayBar(yes, waybar), and then start  SFWBar, the tray will work, although with the issue #23.

3 - But If I start SFWBar firstly and then the WayBar, even the WayBar cannot display its tray.

this error is reproducible, I have reproduced it in my laptop and KVM...

In the situation 3 ,waybar will return such an error:

Invalid Status Notifier Item: :*.**(numbers)org.****(such as kde , fcitx5, or somthing else), /StatusNotifierItem
![20220410_23h10m27s_grim](https://user-images.githubusercontent.com/103374784/162644169-2638d4b7-2f56-468b-9b79-2a1a0d32c998.png)

the Log of sfwbar is hard to catch because it constantly return the Log in the Pictures, Since it was started.
![20220410_23h17m10s_grim](https://user-images.githubusercontent.com/103374784/162644164-74fb3c7b-f717-4316-b590-3b419aedba62.png)

BTW, I am not a native English speaker ,If any of these words are confusing, I would like to explain it.

**Comment by Consolatis** [comment] 2022-04-11 00:34
This sounds like the watcher service used by sfwbar not dealing "properly" with the two conflicting "standards" from Gnome and KDE. One expects StatusNotifierItems to register with a DBus object path and the other assumes a static `/StatusNotifierItem` object path and registers with a "well known" DBus name instead.
When I ran into this issue and tried to figure out what is going on it seemed most watcher implementations are using a little trick like this (`obj_path` is the string the StatusNotifierItem uses to register):

```python3
                if obj_path.startswith('/'):
                        # AppIndicator client, just the object path   
                        addr = sender
                else:                                          
                        # Qt client, just a busname 
                        addr = obj_path                                        
                        obj_path = '/StatusNotifierItem'                       
                addr_path = f'{addr}{obj_path}'
```

**Comment by LBCrion** [comment] 2022-04-11 01:11
This certainly sounds like an issue with the watcher implementation. Which
applications with tray icons are you trying to use?

As for #23, this bug was fixed after beta4 which is the latest version in
copr. Let's fix this issue and I can tag a new release to propagate these
fixes.

**Comment by Kratorisa** [comment] 2022-04-13 04:45
Great! I have already tried it in kvm. If the new release taged, I will try it on my laptop.It will allow me to replace WayBar with SFWBar completely.

Thank you for building such a flexible Bar!

BTW, I cannot currently login my account here due to some verification reasons, so if you want to close this issue(when new releases taged?), you can do that       ;-)

Apr 12, 2022 3:00:19 PM LBCrion ***@***.***>:

**Comment by LBCrion** [comment] 2022-04-14 20:21
I tagged beta6 and updated rpm's in copr. It sounds like they are working? I maintain them, but don't have a machine to test them on myself, so would be grateful for a confirmation (or any suggestions for improvement).

**Comment by LBCrion** [comment] 2022-09-05 18:13
Closing as the issue is resolved

**Closed by LBCrion** 2022-09-05 18:13 UTC

**Comment by LBCrion** [comment] 2022-10-11 07:27
This was indeed an issue with the kde version of the spec. I've been
checking if the first character of the path was ':', which works for tray
items using a normal address,  but fails with well known names.

This should be fixed in the latest git.  I'll try to commit the last bit of
code I'm working on for beta5 and will hopefully tag a release in the next
few days.
