### ISSUE TITLE
Wrong XFCE4-TERNMINAl icon in start menu and taskbar

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#174] opened 2024-05-07 12:20 UTC
In my case, the XFCE4-terminal icon is icon of xfce4-termina-setting in the start menu with the taskbar.
Can it be adjusted through the configuration file.
![xfce4-terminal icon](https://github.com/LBCrion/sfwbar/assets/166389780/bfbd0477-e573-47a1-8cd0-ceede938ad4f)

**Comment by knm100** [comment] 2024-05-07 12:34
By the way, start the xfce4-terminal is no problem.  and  haveing the same problem with mouse

**Comment by LBCrion** [comment] 2024-05-07 20:33
Looks like this is happening because xfce4-terminal installs two .desktop
files. One for the program itself and one for settings. Both have the same
executable, but different command line parameters. Let me run some analysis
and see if there is a sensible way to correctly map to the main program
rather than the settings desktop entry.

**Comment by knm100** [comment] 2024-05-08 08:19
When I switched to the latest git rev, the botton of the xfce4-terminal  was back to normal,
 in the bar was back to normal, but the start menu was still wrong. So, now it should just be a matter of startmenu.widget
![swappy-20240508-161329](https://github.com/LBCrion/sfwbar/assets/166389780/97026d72-7571-43d7-992f-b72a3293c957)

**Comment by LBCrion** [comment] 2024-05-08 17:16
Ok, it looks like this is due to an action section clobbering the values
from the main section. I added a simplistic fix for this for now, but I
plan to write a desktop entry module eventually for a more 'correct' fix.

**Comment by knm100** [comment] 2024-05-09 01:39
good news, thank your!  Hope sfwbar is getting better and better.

**Comment by knm100** [comment] 2024-05-16 06:38
Sometiomes, this probelm go back. But the number of events is very small, usually logout and login can solved it.

**Comment by LBCrion** [comment] 2024-05-16 17:17
Does this happen for the entire session? I.e. if you open more terminal windows, do they all pick up a wrong icon? Also, do you ever get a wrong icon in a session where previous terminals had a correct icon?

**Comment by knm100** [comment] 2024-05-17 03:04
> Does this happen for the entire session?

I don't remember that very well, I'll make a note of it when it comes out.


> if you open more terminal windows, do they all pick up a wrong icon?

I haven't tried it before, at least not now


Also, do you ever get a wrong icon in a session where previous terminals had a correct icon?
I don't remember that very well, I'll make a note of it when it comes out.

**Comment by knm100** [comment] 2024-05-17 05:27
> Does this happen for the entire session?
it didn't , sometimes, the icon of xfce4-terminal was normal before the abnormality icon.
![Uploading swappy-20240517-131859.jpeg…]()

**Comment by LBCrion** [comment] 2024-05-17 06:44
This is caused by xfce installing two desktop entries. xfce4-terminal.desktop and xfce4-terminal-settings.desktop. Neither has a ``Name`` field matching the programs application id. And both have the ``Exec`` field matching the application id. GIO assign's the equal ranking in icon lookup algorithm.

I added an additional preference in the latest git version, to check the desktop entry filename as a first preference. Can you test that please to see if that helps?

**Comment by knm100** [comment] 2024-05-18 11:09
This issue has not happened again in the past day

**Comment by knm100** [comment] 2024-05-23 03:58
Today, This issue happend  again.  Maybe refer to fuzzel（or wofi) , I never went wrong with the xfce4-terminimal icon when I used it

**Comment by knm100** [comment] 2024-05-23 03:59
Today, This issue happend  again. 
Maybe refer to fuzzel（or wofi) , I never went wrong with the xfce4-terminimal icon when I used it.

**Comment by LBCrion** [comment] 2024-05-23 07:22
I see why.  Can you try the latest git please?

**Comment by LBCrion** [comment] 2024-05-23 07:23
Actually,  please hold off.  Need to fix a bug.

**Comment by knm100** [comment] 2024-05-23 07:34
OK

**Comment by LBCrion** [comment] 2024-05-23 17:04
This should be good to test now. Please let me know if you encounter this
issue or the volume icon issue again.

**Comment by LBCrion** [comment] 2024-06-01 07:06
Hi,  just wanted to check if you encountered either of these issues with the latest git version?

**Comment by knm100** [comment] 2024-06-01 11:03
Haven't encountered it yet

**Closed** 2024-07-09 06:08 UTC
